apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-manual
  namespace: web-servers
  labels:
    app: nginx-manual
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-manual
  template:
    metadata:
      labels:
        app: nginx-manual
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-manual
  namespace: web-servers
spec:
  selector:
    app: nginx-manual
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
